### ISSUE TITLE
What to do if changes to Jekyll site are not reflected on hosted site?

### ISSUE THREAD

**Issue by Ulysse33** [dcycle/dcycleu#2]
Lorsque je modifie la page de mon blogue les modifications n'apparaisse plus. Pourquoi? Pouvez-vous me rembourser le temps que j'ai perdu (75$ + taxes)? Merci et au plaisir,

**Comment by alberto56** [comment]
SVP me donner l'URL de ton projet sur GitHub (là où tu vois le code source), ainsi que l'URL du site tel qu'il devrait apparaître une fois publié.

**Comment by alberto56** [comment]
OK, j'ai eu l'info:

http://ulysse33.github.io/startbootstrap-clean-blog-jekyll/
https://github.com/Ulysse33/startbootstrap-clean-blog-jekyll

Est-ce que GitHub t'a envoyé un email du genre "An error occurred when publishing your site"? Si oui, SVP mettre le contenu ici.

**Comment by alberto56** [comment]
Your site code looks fine. 

Please confirm that your email address has been _confirmed_. You must make sure you click on the confirm email link that github sent you (see http://stackoverflow.com/questions/20422279)

See also https://help.github.com/articles/verifying-your-email-address/

If your email address is confirmed, but you still don't see the updates, please add me (alberto56) as an administrator of your project, and I'll look into it.

**Comment by alberto56** [comment]
Just added [some clarification to the course](https://github.com/dcycleproject/dcycleu/commit/b68ea80b3795a3e3f9126750ec098320f4a87f69). @Ulysse33 please close this issue if that is satisfactory.
